# Generated by Django 2.2.1 on 2019-06-04 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments_app', '0002_nurse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateField(default=datetime.date(2019, 6, 4)),
        ),
    ]
